# Generated by Django 2.2.4 on 2019-08-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0002_auto_20190817_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='workTime',
            field=models.IntegerField(null=True, verbose_name='Часы работы'),
        ),
    ]
