# Generated by Django 2.2.4 on 2019-08-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0003_auto_20190817_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='name',
            field=models.CharField(default='Выходной', max_length=20, null=True, verbose_name='Название'),
        ),
    ]
