# Generated by Django 2.2.4 on 2019-08-23 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_api', '0004_eventmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='eventmodel',
            unique_together={('owner', 'date')},
        ),
    ]
