# Generated by Django 2.2.4 on 2019-08-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0005_auto_20190823_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='name',
            field=models.CharField(default='День', max_length=20, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
